[package]
name = "arma3-openshock"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arma-rs = "=1.13.0"
uuid = "1"

[lib]
name = "arma3_openshock"
crate-type = ["cdylib"]
